# Generated by Django 5.1.2 on 2024-10-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
